name: Build and release Omni desktop

on: pull_request

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build app
        run: |
          yarn install --ignore-scripts
          yarn package

      - name: Debug
        run: ls -lh ./release/build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifats
          path: "./release/build/*.dmg"

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build app
        run: |
          yarn
          yarn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifats
          path: "./release/build/*.exe"


  releas-project:
    name: Release Omni build-project
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifats

      - name: Debug
        run: ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Test release"
          tag_name: v0.0.2
          files: |
            *.dmg
            *.exe
